### PR TITLE
Fix Composer autoload generation

### PR DESCRIPTION
**Pull request by wilsenhc**
Examples were updated to make sure it works

### CODE REVIEW

**Comment by devvoh** [comment]
Hey @wilsenhc, it's awesome that you're fixing this up, _however_, honesty dictates that I mention I have little personal incentive to continue developing this library. If you want to fork it, I would be willing to abandon and redirect to that fork if you want 🙂

**Comment by devvoh** [comment]
Especially because I'm not proud of how little composer experience I had when I start this 😂

**Comment by wilsenhc** [comment]
I'd be willing to take it on. I'm just not sure how to maintain a Package myself haha

I installed it because based on the examples, it is exactly what I needed in my project and what was closer to the implementation I needed

**Comment by devvoh** [comment]
Alright. I'll do one last push of improvement soon and get this thing working properly with the experience I've gained since 😂 

After that I'll mark this package as abandoned. Anyone who wants to fork (you or someone else) can then take over if further development is found worthy 😁

**Comment by devvoh** [comment]
@wilsenhc See https://github.com/devvoh/fixed-width/issues/8 for the next step 😄

**Comment by devvoh** [comment]
Though I appreciate the effort, the future for this library should be the next version -- 0.3.0. See open PR.

**Pull request closed without merging**
